/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: {
          50: '#E8F3E8',
          100: '#C5E2C5',
          200: '#A2D1A2',
          300: '#7FC07F',
          400: '#5CAF5C',
          500: '#4F8B4E',
          600: '#3D6F3C',
          700: '#2D5E2C',
          800: '#1E421D',
          900: '#0F2A0E',
        },
        success: { DEFAULT: '#52C41A', bg: '#F6FFED' },
        error: { DEFAULT: '#FF4D4F', bg: '#FFF1F0' },
        warning: { DEFAULT: '#FAAD14', bg: '#FFFBE6' },
        info: { DEFAULT: '#1890FF', bg: '#E6F7FF' },
        text: {
          primary: '#1A1A1A',
          secondary: '#666666',
          placeholder: '#BFBFBF',
          disabled: '#D9D9D9',
          inverse: '#FFFFFF',
        },
        bg: {
          primary: '#F5F7F5',
          secondary: '#FFFFFF',
          tertiary: '#FAFAFA',
          overlay: 'rgba(0,0,0,0.45)',
        },
        border: { DEFAULT: '#E8ECEA', light: '#F0F2F0' },
        divider: '#E8ECEA',
        correct: '#52C41A',
        wrong: '#FF4D4F',
        mastered: '#52C41A',
        forgotten: '#FF4D4F',
        reviewing: '#FAAD14',
        new: '#1890FF',
      },
      fontFamily: {
        base: [
          '-apple-system',
          'BlinkMacSystemFont',
          '"PingFang SC"',
          '"Microsoft YaHei"',
          '"Helvetica Neue"',
          'Arial',
          'sans-serif',
        ],
        english: ['"SF Pro Display"', '"Helvetica Neue"', 'Arial', 'sans-serif'],
        emotion: ['"PingFang SC"', '"Microsoft YaHei"', 'cursive', 'sans-serif'],
      },
      fontSize: {
        xs: ['10px', { lineHeight: '1.2' }],
        sm: ['12px', { lineHeight: '1.5' }],
        base: ['14px', { lineHeight: '1.5' }],
        md: ['15px', { lineHeight: '1.5' }],
        lg: ['16px', { lineHeight: '1.5' }],
        xl: ['18px', { lineHeight: '1.5' }],
        '2xl': ['20px', { lineHeight: '1.5' }],
        '3xl': ['22px', { lineHeight: '1.2' }],
        '4xl': ['24px', { lineHeight: '1.2' }],
        '5xl': ['28px', { lineHeight: '1.2' }],
        '6xl': ['32px', { lineHeight: '1.2' }],
        '7xl': ['40px', { lineHeight: '1.2' }],
      },
      spacing: {
        '0': '0px',
        '1': '2px',
        '2': '4px',
        '3': '6px',
        '4': '8px',
        '5': '10px',
        '6': '12px',
        '7': '14px',
        '8': '16px',
        '9': '18px',
        '10': '20px',
        '12': '24px',
        '14': '28px',
        '16': '32px',
        '18': '36px',
        '20': '40px',
        '24': '48px',
        '32': '64px',
      },
      borderRadius: {
        none: '0px',
        sm: '4px',
        md: '8px',
        lg: '12px',
        xl: '16px',
        '2xl': '20px',
        '3xl': '24px',
        full: '9999px',
      },
      boxShadow: {
        xs: '0 1px 2px rgba(0,0,0,0.04)',
        sm: '0 1px 4px rgba(0,0,0,0.06)',
        md: '0 4px 12px rgba(0,0,0,0.08)',
        lg: '0 8px 24px rgba(0,0,0,0.12)',
        xl: '0 12px 40px rgba(0,0,0,0.16)',
        '2xl': '0 24px 64px rgba(0,0,0,0.20)',
        card: '0 2px 8px rgba(0,0,0,0.06), 0 1px 2px rgba(0,0,0,0.04)',
      },
      animation: {
        'card-flip': 'card-flip 0.3s ease-in-out forwards',
        'slide-out-right': 'slide-out-right 0.4s ease-in-out forwards',
        'slide-in-left': 'slide-in-left 0.4s ease-in-out forwards',
        'toast-in': 'toast-in 0.25s ease-out forwards',
        'toast-out': 'toast-out 0.25s ease-in forwards',
        'modal-in': 'modal-in 0.35s ease-out forwards',
        'modal-out': 'modal-out 0.35s ease-in forwards',
        'sheet-in': 'sheet-in 0.35s ease-out forwards',
        'sheet-out': 'sheet-out 0.35s ease-in forwards',
        'skeleton-pulse': 'skeleton-pulse 1.5s ease-in-out infinite',
      },
      keyframes: {
        'card-flip': {
          '0%': { transform: 'perspective(800px) rotateY(0deg)' },
          '100%': { transform: 'perspective(800px) rotateY(180deg)' },
        },
        'slide-out-right': {
          '0%': { transform: 'translateX(0)', opacity: '1' },
          '100%': { transform: 'translateX(100px)', opacity: '0' },
        },
        'slide-in-left': {
          '0%': { transform: 'translateX(-30px)', opacity: '0' },
          '100%': { transform: 'translateX(0)', opacity: '1' },
        },
        'toast-in': {
          '0%': { transform: 'translateY(20px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        'toast-out': {
          '0%': { transform: 'translateY(0)', opacity: '1' },
          '100%': { transform: 'translateY(20px)', opacity: '0' },
        },
        'modal-in': {
          '0%': { transform: 'scale(0.95)', opacity: '0' },
          '100%': { transform: 'scale(1)', opacity: '1' },
        },
        'modal-out': {
          '0%': { transform: 'scale(1)', opacity: '1' },
          '100%': { transform: 'scale(0.95)', opacity: '0' },
        },
        'sheet-in': {
          '0%': { transform: 'translateY(100%)' },
          '100%': { transform: 'translateY(0)' },
        },
        'sheet-out': {
          '0%': { transform: 'translateY(0)' },
          '100%': { transform: 'translateY(100%)' },
        },
        'skeleton-pulse': {
          '0%': { opacity: '0.6' },
          '50%': { opacity: '1' },
          '100%': { opacity: '0.6' },
        },
      },
    },
  },
  plugins: [],
};
